name: CD Pipeline

on:
  workflow_run: 
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  simple_CD_job:
    runs-on: ubuntu-20.04 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Deploy to production
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }} 