name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_CI_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4 # GitHub reusable actions
      
      - name: Setup Node.js v20
        uses: actions/setup-node@v4 # GitHub reusable actions
        with: 
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
