name: Discord Notifications

on:
  workflow_run:
    workflows: ["CI Pipeline", "CD Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  discord_notification:
    runs-on: ubuntu-24.04

    steps:
      - name: Workflow Status
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          nodetail: true
          title: "${{ github.event.workflow_run.name }} - ${{ github.event.workflow_run.conclusion }}"
          description: |
            **Repository:** [${{ github.repository }}](${{ github.event.repository.html_url }})
            **Branch:** [${{ github.event.workflow_run.head_branch }}](${{ github.event.workflow_run.head_repository.html_url }}/tree/${{github.event.workflow_run.head_branch }})
            **Commit:** [${{ github.event.workflow_run.head_commit.message }}](${{ github.event.workflow_run.head_repository.html_url }}/commit/${{ github.event.workflow_run.head_sha }}) by ${{ github.event.workflow_run.triggering_actor }}
            **Deployment:** ${{ github.event.workflow_run.name == 'CD Pipeline' && github.event.workflow_run.conclusion == 'success' && 'Deployed successfully 🎉 to https://full-stack-open-pokedex-m6v6.onrender.com' || github.event.workflow_run.conclusion == 'failure' && 'Failed ❌ Please check logs at https://github.com/prak112/full-stack-open-pokedex/actions/' || github.event.workflow_run.name == 'CD Pipeline' && github.event.workflow_run.conclusion == 'skipped' && 'Cancelled due to CI failure' || 'Awaiting CD workflow status...' }}
    
          color: ${{ github.event.workflow_run.conclusion == 'success' && '0x3CF013' || github.event.workflow_run.conclusion == 'failure' && '0xBF0A13' || '0x3498DB' }}
          username: "GitHub Actions"

          