name: Periodic Checks

on: 
  schedule:
    - cron: '45 14 19-29 3 *'

jobs:
  health_check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-m6v6.onrender.com
          max-attempts: 3 
          retry-delay: 5s

